version: '3.11.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock_app_image_flask
    container_name: stock_flask
    ports: 
      - '5001:5000'
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"